<!doctype html>
<html lang="en">


























































































</html></body>  </div>    <div class="muted" style="font-size:13px">Edit: <code>resources/views/resume_en.blade.php</code> • Thai version: <a href="{{ route('resume.show', 'th') }}">เรซูเม่ (TH)</a></div>    <hr>    </section>      </div>        <strong>B.Sc. in Software Engineering</strong> — <span class="muted">[University] • [Graduation]</span>      <div>      <h2>Education</h2>    <section class="section">    </section>      </div>        <div class="muted">Features: scheduling, email notifications, real-time confirmations</div>        <strong>Online Booking System</strong> — Node.js, Express, PostgreSQL, React      <div style="margin-top:6px">      </div>        <div class="muted">Features: registration, email verification, role-based access, report export</div>        <strong>Member Management System</strong> — Laravel, Vue.js, MySQL      <div>      <h2>Selected Projects</h2>    <section class="section">    </section>      </div>        </ul>          <li>Optimized queries and reduced page load time by ~30%</li>          <li>Designed & implemented REST APIs for frontend with unit tests</li>          <li>Built user management modules with Laravel and MySQL</li>        <ul>        <strong>Junior Software Engineer</strong> — <span class="muted">[Company]</span>      <div>      <h2>Experience (Sample)</h2>    <section class="section">    </section>      </div>        <div class="skill">Docker</div>        <div class="skill">Git</div>        <div class="skill">RESTful API</div>        <div class="skill">MySQL / PostgreSQL</div>        <div class="skill">Vue.js / React</div>        <div class="skill">TypeScript</div>        <div class="skill">PHP (Laravel)</div>        <div class="skill">JavaScript</div>      <div class="skills">      <h2>Key Skills</h2>    <section class="section">    </section>      <p>Software engineer with experience in building web applications (frontend & backend) using JavaScript, PHP (Laravel), MySQL, and Git. Comfortable working in Agile teams and focused on writing maintainable, testable, and scalable code.</p>      <h2>Professional Summary</h2>    <section class="section">    </header>      </div>        <a class="btn" href="{{ route('resume.download.pdf', ['lang' => 'en']) }}" style="background:#c0392b">Download PDF</a>        <a class="btn" href="{{ route('resume.download.markdown', ['lang' => 'en']) }}" style="background:#6c757d">Download MD</a>        <a class="btn" href="{{ route('resume.download.html', ['lang' => 'en']) }}" style="background:#0b8043">Download HTML</a>        <a class="btn" href="{{ route('resume.show', 'en') }}">View</a>      <div class="actions">      </div>        <div>GitHub: <a href="https://github.com/siwakorn" target="_blank">github.com/siwakorn</a> • LinkedIn: <a href="https://linkedin.com/in/siwakorn" target="_blank">linkedin.com/in/siwakorn</a></div>        <div>Phone: <strong>[phone]</strong> • Email: <strong>[email@example.com]</strong></div>      <div style="margin-top:8px">      <div class="muted">Major: Software Engineering</div>      <h1>Siwakorn Kleebmek</h1>    <header>  <div class="container"><body></head>  </style>    @media print{.actions{display:none}}    .btn{display:inline-block;padding:8px 12px;border-radius:6px;background:#1a73e8;color:#fff;text-decoration:none;font-size:14px}    .actions{margin-t
op:14px}    .skill{background:#f1f1f1;padding:6px 8px;border-radius:6px;font-size:13px}    .skills{display:flex;flex-wrap:wrap;gap:8px}    .section{margin:18px 0}    .muted{color:#666;font-size:14px}    h2{margin:12px 0 6px;font-size:16px;color:#333}    h1{margin:0;font-size:26px}    .container{max-width:800px;margin:0 auto;padding:24px;border:1px solid #eee}    body{font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif; color:#111; line-height:1.4; margin:0; padding:24px;}
  <style>  <title>Resume — Siwakorn Kleebmek</title>  <meta name="viewport" content="width=device-width, initial-scale=1">  <meta charset="utf-8"><head>
